require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'

target 'employee' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

  pod 'react-native-pusher-push-notifications', :path => '../node_modules/react-native-pusher-push-notifications'

  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'

  target 'employeeTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
#  use_flipper!
#  post_install do |installer|
#    flipper_post_install(installer)
#  end
end

target 'employee-tvOS' do
  # Pods for employee-tvOS

  target 'employee-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
